"""
Analytics Export Service

Generates downloadable CI/CD YAML bundles for:
  - Databricks Genie Spaces  → downloads/spaces/<name>/
  - Lakeview Dashboards      → downloads/dashboards/<name>/

Each bundle is a ZIP archive with human-readable YAML files that can be
version-controlled and used as input to a customer's own deployment engine.

YAML bundle layouts
-------------------
Genie Space:
    config.yaml        – space metadata + deployment config
    tables.yaml        – metric views + plain tables registered in the space
    instructions.yaml  – text instructions, join specs, SQL snippets
    questions.yaml     – sample questions + example SQL queries

Lakeview Dashboard:
    config.yaml        – dashboard metadata + deployment config
    datasets.yaml      – dataset SQL queries powering the widgets
    pages.yaml         – page layout with widget specs (human-readable)
"""
import json
import logging
import re
from typing import Any, Dict, List, Optional

import yaml

from src.repositories.dashboard_repository import DashboardRepository
from src.repositories.genie_repository import GenieRepository
from src.schemas.analytics_export import ExportFile
from src.schemas.genie import GenieAuthConfig

logger = logging.getLogger(__name__)


def _safe_folder_name(s: str) -> str:
    """Convert a display name to a safe lowercase folder name."""
    safe = re.sub(r"[^a-zA-Z0-9_\-]", "_", s).strip("_").lower()
    return safe[:80] or "export"


def _yaml_dump(data: Any) -> str:
    """Dump data to a nicely formatted YAML string."""
    return yaml.dump(
        data,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
        indent=2,
        width=120,
    )


# ──────────────────────────────────────────────────────────────────────────────
# Genie Space → YAML
# ──────────────────────────────────────────────────────────────────────────────

def _genie_space_to_files(space_data: Dict[str, Any]) -> List[ExportFile]:
    """Convert the raw Genie space API response to a list of YAML ExportFiles."""

    # The API may return serialized_space as a JSON string or an embedded dict.
    serialized_raw = space_data.get("serialized_space") or "{}"
    if isinstance(serialized_raw, str):
        try:
            spec: Dict[str, Any] = json.loads(serialized_raw)
        except (json.JSONDecodeError, ValueError):
            spec = {}
    else:
        spec = serialized_raw or {}

    space_id = space_data.get("space_id") or space_data.get("id") or ""
    title = space_data.get("title") or space_data.get("display_name") or "Genie Space"
    warehouse_id = space_data.get("warehouse_id") or ""
    description = space_data.get("description") or ""

    # ── config.yaml ──────────────────────────────────────────────────────────
    config_data: Dict[str, Any] = {
        "apiVersion": "genie/v1",
        "kind": "GenieSpace",
        "metadata": {
            "name": _safe_folder_name(title),
            "space_id": space_id,
        },
        "spec": {
            "title": title,
            "description": description,
            "warehouse_id": warehouse_id,
        },
    }

    config_yaml = (
        "# Genie Space CI/CD Configuration — generated by Kasal\n"
        "# Redeploy by calling the Databricks Genie API:\n"
        "#   POST /api/2.0/genie/spaces   (create)\n"
        "#   PATCH /api/2.0/genie/spaces/{id}  (update)\n\n"
    ) + _yaml_dump(config_data)

    # ── tables.yaml ──────────────────────────────────────────────────────────
    data_sources: Dict[str, Any] = spec.get("data_sources") or {}

    metric_views: List[str] = [
        t.get("identifier", "") for t in (data_sources.get("metric_views") or [])
        if t.get("identifier")
    ]
    plain_tables: List[str] = [
        t.get("identifier", "") for t in (data_sources.get("tables") or [])
        if t.get("identifier")
    ]

    tables_data: Dict[str, Any] = {}
    if metric_views:
        tables_data["metric_views"] = metric_views
    if plain_tables:
        tables_data["tables"] = plain_tables
    if not tables_data:
        tables_data["metric_views"] = []
        tables_data["tables"] = []

    tables_yaml = (
        "# Tables and Metric Views registered in this Genie Space\n"
        "# Add or remove entries, then redeploy with your engine.\n\n"
    ) + _yaml_dump(tables_data)

    # ── instructions.yaml ─────────────────────────────────────────────────────
    instructions_block: Dict[str, Any] = spec.get("instructions") or {}

    # Text instructions: [{"id": ..., "content": ["..."]}]
    text_parts: List[str] = []
    for ti in (instructions_block.get("text_instructions") or []):
        content = ti.get("content") or []
        text_parts.extend(content if isinstance(content, list) else [content])
    text_instructions_str = "\n".join(text_parts)

    # Join specs: [{"left": {...}, "right": {...}, "sql": [...]}]
    join_specs_out: List[Dict[str, Any]] = []
    for js in (instructions_block.get("join_specs") or []):
        left_obj = js.get("left") or {}
        right_obj = js.get("right") or {}
        sql_parts: List[str] = [
            s for s in (js.get("sql") or []) if s and not s.startswith("--rt=")
        ]
        join_specs_out.append({
            "left_table": left_obj.get("identifier", ""),
            "right_table": right_obj.get("identifier", ""),
            "join_condition": " ".join(sql_parts),
        })

    # SQL snippets
    snippets: Dict[str, Any] = instructions_block.get("sql_snippets") or {}
    expressions_out: List[Dict[str, Any]] = [
        {"display_name": e.get("display_name", ""), "sql": " ".join(e.get("sql") or [])}
        for e in (snippets.get("expressions") or [])
    ]
    measures_out: List[Dict[str, Any]] = [
        {
            "display_name": m.get("display_name", ""),
            "sql": " ".join(m.get("sql") or []),
            "instruction": " ".join(m.get("instruction") or []),
        }
        for m in (snippets.get("measures") or [])
    ]
    filters_out: List[Dict[str, Any]] = [
        {"display_name": f.get("display_name", ""), "sql": " ".join(f.get("sql") or [])}
        for f in (snippets.get("filters") or [])
    ]

    instructions_data: Dict[str, Any] = {}
    if text_instructions_str:
        instructions_data["text_instructions"] = text_instructions_str
    if join_specs_out:
        instructions_data["join_specs"] = join_specs_out
    sql_snippets_data: Dict[str, Any] = {}
    if expressions_out:
        sql_snippets_data["expressions"] = expressions_out
    if measures_out:
        sql_snippets_data["measures"] = measures_out
    if filters_out:
        sql_snippets_data["filters"] = filters_out
    if sql_snippets_data:
        instructions_data["sql_snippets"] = sql_snippets_data

    instructions_yaml = (
        "# Genie Space Instructions — controls AI behavior and data understanding\n"
        "# text_instructions: free-form guidance for the Genie AI\n"
        "# join_specs: how dimension tables relate to metric views\n"
        "# sql_snippets: reusable SQL expressions, measures, and filters\n\n"
    ) + _yaml_dump(instructions_data if instructions_data else {"text_instructions": ""})

    # ── questions.yaml ───────────────────────────────────────────────────────
    config_block: Dict[str, Any] = spec.get("config") or {}
    sample_questions_out: List[str] = [
        " ".join(sq.get("question") or []) if isinstance(sq.get("question"), list)
        else str(sq.get("question", ""))
        for sq in (config_block.get("sample_questions") or [])
        if sq.get("question")
    ]

    example_sqls_out: List[Dict[str, Any]] = [
        {
            "question": " ".join(eq.get("question") or []) if isinstance(eq.get("question"), list)
            else str(eq.get("question", "")),
            "sql": " ".join(eq.get("sql") or []) if isinstance(eq.get("sql"), list)
            else str(eq.get("sql", "")),
        }
        for eq in (instructions_block.get("example_question_sqls") or [])
    ]

    questions_data: Dict[str, Any] = {
        "sample_questions": sample_questions_out or [],
        "example_sqls": example_sqls_out or [],
    }

    questions_yaml = (
        "# Sample questions shown to users + curated example SQL queries\n"
        "# sample_questions: surface these in the Genie UI as suggestions\n"
        "# example_sqls: show the AI how to answer specific question patterns\n\n"
    ) + _yaml_dump(questions_data)

    return [
        ExportFile(path="config.yaml", content=config_yaml),
        ExportFile(path="tables.yaml", content=tables_yaml),
        ExportFile(path="instructions.yaml", content=instructions_yaml),
        ExportFile(path="questions.yaml", content=questions_yaml),
    ]


# ──────────────────────────────────────────────────────────────────────────────
# Lakeview Dashboard → YAML
# ──────────────────────────────────────────────────────────────────────────────

def _widget_layout_to_yaml_dict(layout_item: Dict[str, Any]) -> Dict[str, Any]:
    """
    Convert a single Lakeview widget layout entry to a clean, human-readable dict.

    Handles: text, counter, bar, line, pie, table, filter-multi-select,
             filter-single-select, filter-date-range-picker.
    """
    widget: Dict[str, Any] = layout_item.get("widget") or {}
    position: Dict[str, Any] = layout_item.get("position") or {}

    widget_name: str = widget.get("name") or "unnamed"
    pos_dict = {
        "x": position.get("x", 0),
        "y": position.get("y", 0),
        "width": position.get("width", 3),
        "height": position.get("height", 4),
    }

    spec: Dict[str, Any] = widget.get("spec") or {}
    widget_type: str = spec.get("widgetType") or ""
    queries: List[Dict[str, Any]] = widget.get("queries") or []

    # ── Text widget ──────────────────────────────────────────────────────────
    if not widget_type and widget.get("multilineTextboxSpec"):
        lines: List[str] = widget["multilineTextboxSpec"].get("lines") or []
        return {
            "type": "text",
            "name": widget_name,
            "position": pos_dict,
            "content": "".join(lines),
        }

    # ── Filter widgets ────────────────────────────────────────────────────────
    if widget_type.startswith("filter-"):
        frame = spec.get("frame") or widget.get("frame") or {}
        title = frame.get("title") or widget_name

        encodings: Dict[str, Any] = spec.get("encodings") or {}
        fields_enc: List[Dict[str, Any]] = encodings.get("fields") or []

        dataset_name = ""
        field_name = ""
        display_name = ""
        if queries:
            q = (queries[0].get("query") or {})
            dataset_name = q.get("datasetName") or ""
        if fields_enc:
            field_name = fields_enc[0].get("fieldName") or ""
            display_name = fields_enc[0].get("displayName") or field_name

        return {
            "type": widget_type,
            "name": widget_name,
            "position": pos_dict,
            "title": title,
            "dataset": dataset_name,
            "field": field_name,
            "displayName": display_name,
        }

    # ── Common helpers for data widgets ──────────────────────────────────────
    frame: Dict[str, Any] = spec.get("frame") or widget.get("frame") or {}
    title: str = frame.get("title") or widget_name
    encodings: Dict[str, Any] = spec.get("encodings") or {}

    dataset_name = ""
    raw_fields: List[Dict[str, Any]] = []
    if queries:
        q = queries[0].get("query") or {}
        dataset_name = q.get("datasetName") or ""
        raw_fields = q.get("fields") or []

    fields_out: List[Dict[str, Any]] = [
        {"name": f.get("name", ""), "expression": f.get("expression", "")}
        for f in raw_fields
    ]

    # ── Counter ───────────────────────────────────────────────────────────────
    if widget_type == "counter":
        value_enc: Dict[str, Any] = encodings.get("value") or {}
        return {
            "type": "counter",
            "name": widget_name,
            "position": pos_dict,
            "title": title,
            "dataset": dataset_name,
            "value_field": value_enc.get("fieldName") or "",
            "fields": fields_out,
        }

    # ── Table ─────────────────────────────────────────────────────────────────
    if widget_type == "table":
        columns_enc: List[Dict[str, Any]] = encodings.get("columns") or []
        columns_out = [
            {"field": c.get("fieldName", ""), "displayName": c.get("displayName", "")}
            for c in columns_enc
        ]
        return {
            "type": "table",
            "name": widget_name,
            "position": pos_dict,
            "title": title,
            "dataset": dataset_name,
            "columns": columns_out,
            "fields": fields_out,
        }

    # ── Bar / Line / Pie charts ───────────────────────────────────────────────
    if widget_type in ("bar", "line", "pie"):
        x_enc: Dict[str, Any] = encodings.get("x") or {}
        y_enc: Dict[str, Any] = encodings.get("y") or {}
        color_enc: Optional[Dict[str, Any]] = encodings.get("color")

        out: Dict[str, Any] = {
            "type": widget_type,
            "name": widget_name,
            "position": pos_dict,
            "title": title,
            "dataset": dataset_name,
            "x": {
                "field": x_enc.get("fieldName") or "",
                "type": (x_enc.get("scale") or {}).get("type") or "categorical",
            },
            "y": {
                "field": y_enc.get("fieldName") or "",
                "type": (y_enc.get("scale") or {}).get("type") or "quantitative",
            },
            "fields": fields_out,
        }
        if color_enc:
            out["color"] = {"field": color_enc.get("fieldName") or ""}
        return out

    # ── Fallback ───────────────────────────────────────────────────────────────
    return {
        "type": widget_type or "unknown",
        "name": widget_name,
        "position": pos_dict,
        "title": title,
        "dataset": dataset_name,
        "fields": fields_out,
        "raw_spec": spec,
    }


def _dashboard_to_files(dashboard_data: Dict[str, Any]) -> List[ExportFile]:
    """Convert the raw Lakeview dashboard API response to a list of YAML ExportFiles."""

    dashboard_id: str = dashboard_data.get("dashboard_id") or ""
    display_name: str = dashboard_data.get("display_name") or "Dashboard"
    warehouse_id: str = dashboard_data.get("warehouse_id") or ""
    parent_path: str = dashboard_data.get("parent_path") or "/Workspace/Shared"

    # Parse the serialized_dashboard JSON string
    serialized_raw = dashboard_data.get("serialized_dashboard") or "{}"
    if isinstance(serialized_raw, str):
        try:
            spec: Dict[str, Any] = json.loads(serialized_raw)
        except (json.JSONDecodeError, ValueError):
            spec = {}
    else:
        spec = serialized_raw or {}

    pages_raw: List[Dict[str, Any]] = spec.get("pages") or []
    datasets_raw: List[Dict[str, Any]] = spec.get("datasets") or []

    # ── config.yaml ──────────────────────────────────────────────────────────
    config_data: Dict[str, Any] = {
        "apiVersion": "lakeview/v1",
        "kind": "Dashboard",
        "metadata": {
            "name": _safe_folder_name(display_name),
            "dashboard_id": dashboard_id,
        },
        "spec": {
            "title": display_name,
            "warehouse_id": warehouse_id,
            "parent_path": parent_path,
            "publish": True,
        },
    }

    config_yaml = (
        "# Lakeview Dashboard CI/CD Configuration — generated by Kasal\n"
        "# Redeploy with the Databricks Lakeview REST API:\n"
        "#   POST /api/2.0/lakeview/dashboards   (create)\n"
        "#   PATCH /api/2.0/lakeview/dashboards/{id}  (update)\n"
        "#   POST  /api/2.0/lakeview/dashboards/{id}/published  (publish)\n\n"
    ) + _yaml_dump(config_data)

    # ── datasets.yaml ─────────────────────────────────────────────────────────
    datasets_out: List[Dict[str, Any]] = []
    for ds in datasets_raw:
        ds_entry: Dict[str, Any] = {
            "name": ds.get("name") or "",
            "displayName": ds.get("displayName") or ds.get("display_name") or "",
            "query": ds.get("query") or "",
        }
        datasets_out.append(ds_entry)

    datasets_yaml = (
        "# Dashboard Dataset Queries\n"
        "# Each dataset is a SQL query that powers one or more widgets.\n"
        "# For UCMV-backed dashboards use MEASURE() syntax:\n"
        "#   MEASURE(metric_name)  — aggregated by the widget encodings\n\n"
        "datasets:\n"
    )
    # Emit datasets with literal block scalars for multi-line SQL
    for ds in datasets_out:
        datasets_yaml += f"  - name: {ds['name']}\n"
        if ds["displayName"]:
            datasets_yaml += f"    displayName: {json.dumps(ds['displayName'])}\n"
        sql = ds["query"].strip()
        if "\n" in sql:
            # Literal block scalar keeps SQL indentation
            indented = "\n".join("      " + line for line in sql.splitlines())
            datasets_yaml += f"    query: |\n{indented}\n"
        else:
            datasets_yaml += f"    query: {json.dumps(sql)}\n"
        datasets_yaml += "\n"

    # ── pages.yaml ────────────────────────────────────────────────────────────
    pages_out: List[Dict[str, Any]] = []
    for page in pages_raw:
        page_name: str = page.get("name") or ""
        page_display: str = page.get("displayName") or page.get("display_name") or page_name
        layout: List[Dict[str, Any]] = page.get("layout") or []

        widgets_out: List[Dict[str, Any]] = [
            _widget_layout_to_yaml_dict(item) for item in layout
        ]

        pages_out.append({
            "name": page_name,
            "displayName": page_display,
            "widgets": widgets_out,
        })

    pages_yaml = (
        "# Dashboard Pages and Widget Layout\n"
        "# Grid: 6 columns wide. Each row must sum to width=6 (no gaps).\n"
        "#\n"
        "# Widget types: text | counter | bar | line | pie | table\n"
        "#               filter-multi-select | filter-single-select | filter-date-range-picker\n"
        "#\n"
        "# Widget field naming rules:\n"
        "#   dimension: {name: 'col',        expression: '`col`'}\n"
        "#   measure:   {name: 'sum(col)',    expression: 'SUM(`col`)'}\n"
        "#   x/y/value encodings must use the field 'name' exactly\n\n"
    ) + _yaml_dump({"pages": pages_out})

    return [
        ExportFile(path="config.yaml", content=config_yaml),
        ExportFile(path="datasets.yaml", content=datasets_yaml),
        ExportFile(path="pages.yaml", content=pages_yaml),
    ]


# ──────────────────────────────────────────────────────────────────────────────
# Public service
# ──────────────────────────────────────────────────────────────────────────────

class AnalyticsExportService:
    """
    Service that orchestrates fetching resources from Databricks
    and converting them to CI/CD-ready YAML bundles.
    """

    def __init__(self, user_token: Optional[str] = None):
        """
        Args:
            user_token: Optional OBO user token forwarded from the HTTP request.
        """
        self._user_token = user_token

    async def export_genie_space(self, space_id: str) -> Dict[str, Any]:
        """
        Fetch a Genie space from Databricks and convert it to a YAML bundle.

        Returns:
            {
              "space_id": str,
              "space_name": str,
              "folder_name": str,
              "files": List[ExportFile],
            }
        Raises RuntimeError / httpx.HTTPStatusError on failure.
        """
        auth_config = GenieAuthConfig(
            use_obo=bool(self._user_token),
            user_token=self._user_token,
            pat_token=None,
            host=None,
        )
        repo = GenieRepository(auth_config=auth_config)

        space_data = await repo.get_space_details(space_id)
        if not space_data:
            raise ValueError(f"Genie space {space_id!r} not found")

        # GenieRepository.get_space_details returns a GenieSpace Pydantic model.
        # Convert to dict for uniform processing.
        if hasattr(space_data, "model_dump"):
            space_dict: Dict[str, Any] = space_data.model_dump()
        else:
            space_dict = dict(space_data)

        # If the repository strips serialized_space, we need to fetch the raw dict.
        # Check whether the full serialized_space is available; if not, re-fetch via
        # a direct HTTP call using the same auth context.
        if "serialized_space" not in space_dict:
            space_dict = await self._fetch_raw_genie_space(space_id)

        title = space_dict.get("title") or space_dict.get("name") or space_id
        folder_name = _safe_folder_name(title)
        files = _genie_space_to_files(space_dict)

        return {
            "space_id": space_id,
            "space_name": title,
            "folder_name": folder_name,
            "files": files,
        }

    async def _fetch_raw_genie_space(self, space_id: str) -> Dict[str, Any]:
        """Direct HTTP fetch of a Genie space to get the full serialized_space field."""
        import httpx
        from src.utils.databricks_auth import get_auth_context

        auth = await get_auth_context()
        if not auth or not auth.workspace_url:
            raise RuntimeError("No Databricks workspace URL configured")

        token = self._user_token or auth.token
        headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
        url = f"{auth.workspace_url.rstrip('/')}/api/2.0/genie/spaces/{space_id}"

        async with httpx.AsyncClient(timeout=30.0) as client:
            resp = await client.get(url, headers=headers)
            resp.raise_for_status()
            return resp.json()

    async def export_dashboard(self, dashboard_id: str) -> Dict[str, Any]:
        """
        Fetch a Lakeview dashboard from Databricks and convert it to a YAML bundle.

        Returns:
            {
              "dashboard_id": str,
              "dashboard_name": str,
              "folder_name": str,
              "files": List[ExportFile],
            }
        Raises ValueError when not found, httpx.HTTPStatusError on API errors.
        """
        repo = DashboardRepository(user_token=self._user_token)
        dashboard_data = await repo.get_dashboard(dashboard_id)
        await repo.close()

        if not dashboard_data:
            raise ValueError(f"Dashboard {dashboard_id!r} not found")

        display_name = dashboard_data.get("display_name") or dashboard_id
        folder_name = _safe_folder_name(display_name)
        files = _dashboard_to_files(dashboard_data)

        return {
            "dashboard_id": dashboard_id,
            "dashboard_name": display_name,
            "folder_name": folder_name,
            "files": files,
        }

    async def list_dashboards(self, page_size: int = 50) -> List[Dict[str, Any]]:
        """Return a list of all accessible Lakeview dashboards (summary only)."""
        repo = DashboardRepository(user_token=self._user_token)
        result = await repo.list_dashboards(page_size=page_size)
        await repo.close()
        return result
